/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RiskEngineRouteImport } from './routes/risk-engine'
import { Route as PermitsRouteImport } from './routes/permits'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HeatmapRouteImport } from './routes/heatmap'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as IndexRouteImport } from './routes/index'

const RiskEngineRoute = RiskEngineRouteImport.update({
  id: '/risk-engine',
  path: '/risk-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const PermitsRoute = PermitsRouteImport.update({
  id: '/permits',
  path: '/permits',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HeatmapRoute = HeatmapRouteImport.update({
  id: '/heatmap',
  path: '/heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/emergency': typeof EmergencyRoute
  '/heatmap': typeof HeatmapRoute
  '/login': typeof LoginRoute
  '/permits': typeof PermitsRoute
  '/risk-engine': typeof RiskEngineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/emergency': typeof EmergencyRoute
  '/heatmap': typeof HeatmapRoute
  '/login': typeof LoginRoute
  '/permits': typeof PermitsRoute
  '/risk-engine': typeof RiskEngineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/copilot': typeof CopilotRoute
  '/emergency': typeof EmergencyRoute
  '/heatmap': typeof HeatmapRoute
  '/login': typeof LoginRoute
  '/permits': typeof PermitsRoute
  '/risk-engine': typeof RiskEngineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compliance'
    | '/copilot'
    | '/emergency'
    | '/heatmap'
    | '/login'
    | '/permits'
    | '/risk-engine'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compliance'
    | '/copilot'
    | '/emergency'
    | '/heatmap'
    | '/login'
    | '/permits'
    | '/risk-engine'
  id:
    | '__root__'
    | '/'
    | '/compliance'
    | '/copilot'
    | '/emergency'
    | '/heatmap'
    | '/login'
    | '/permits'
    | '/risk-engine'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplianceRoute: typeof ComplianceRoute
  CopilotRoute: typeof CopilotRoute
  EmergencyRoute: typeof EmergencyRoute
  HeatmapRoute: typeof HeatmapRoute
  LoginRoute: typeof LoginRoute
  PermitsRoute: typeof PermitsRoute
  RiskEngineRoute: typeof RiskEngineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/risk-engine': {
      id: '/risk-engine'
      path: '/risk-engine'
      fullPath: '/risk-engine'
      preLoaderRoute: typeof RiskEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permits': {
      id: '/permits'
      path: '/permits'
      fullPath: '/permits'
      preLoaderRoute: typeof PermitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heatmap': {
      id: '/heatmap'
      path: '/heatmap'
      fullPath: '/heatmap'
      preLoaderRoute: typeof HeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplianceRoute: ComplianceRoute,
  CopilotRoute: CopilotRoute,
  EmergencyRoute: EmergencyRoute,
  HeatmapRoute: HeatmapRoute,
  LoginRoute: LoginRoute,
  PermitsRoute: PermitsRoute,
  RiskEngineRoute: RiskEngineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
